export const CREATE_HERO = "CREATE_HERO";
export const FETCHING_HEROS = "FETCHING_HEROS";
export const FETCHING_HEROS_SUCCESS = "FETCHING_HEROS_FAIL";
export const FETCHING_HEROS_FAIL = "FETCHING_HEROS_SUCCESS";
