export const CREATE_HERO = "CREATE_HERO";
export const CREATING_HERO = "CREATING_HERO";
export const CREATING_HERO_SUCCESS = "CREATING_HERO_SUCCESS";
export const FETCHING_HEROS = "FETCHING_HEROS";
export const FETCHING_HEROS_SUCCESS = "FETCHING_HEROS_SUCCESS";
export const FETCHING_HEROS_FAIL = "FETCHING_HEROS_FAIL";
export const DELETING_HEROS_START = "DELETING_HEROS_START";
export const DELETING_HEROS_SUCCESS = "DELETING_HEROS_SUCCESS";
export const DELETING_HEROS_FAIL= "DELETING_HEROS_FAIL";
export const UPDATING_HERO = "UPDATING_HERO";
export const UPDATING_HERO_SUCCESS = "UPDATING_HERO_SUCCESS";
export const UPDATING_HERO_FAIL = "UPDATING_HERO_FAIL";
export const FETCHING_HERO = "FETCHING_HERO";
export const FETCHING_HERO_SUCCESS = "FETCHING_HERO_SUCCESS";
export const FETCHING_HERO_FAIL = "FETCHING_HERO_FAIL";
export const CLEAR_HERO_EDIT = "CLEAR_HERO_EDIT";

